### ISSUE TITLE
Prettier formatting of anonymous types

### ISSUE THREAD

**Issue by pmg23** [stakx/TypeNameFormatter#13]
In 1.0.0-beta, `new {foo="foo", bar=42}.GetType().GetFormattedName()` returns something like `"<>f__AnonymousType5<string, int>"`. This is not wrong, as there is no C# naming convention for anonymous types, but I wonder if the library could return something prettier, e.g. `"{string, int}"`?

**Comment by stakx** [comment]
Cheers for reporting this one. Great to have such a thorough tester on-board! 👍

That's a tough one. To prevent the names of such anonymous types from becoming ambiguous, they'd probably have to include the properties' names as well (AFAIK C# doesn't reuse anonymous types based on the combination of properies' types alone), which would make the name transform computationally more expensive. I'm not quite sure yet whether this is desirable.

Any thoughts on this?

**Comment by pmg23** [comment]
Hi

To elaborate a bit, I can see two major uses of the library. One is source
code generation, and for this purpose it should generate only valid C# (or
Visual Basic), or throw an exception. The other is diagnostics, e.g.
logging, and here it should give a best-efforts result, and never throw.

I suggest a flag "strict mode" for this purpose, defaulting to best-efforts.

In strict mode, anonymous types should not be printable at all (and
similarly, pointer types in VB).

In best-efforts mode, I don't particularly care if there is ambiguity as to
the exact identity of the type in edge cases. We're already not including
namespace by default, let alone assembly etc.

As for anonymous types, although including field names would help
disambiguate, it would not identify the type, as (IIUC) each use of an
anonymous type in the code results in a distinct class being defined - even
if identical in every respect.

So my preference would be exclude field names by default - for brevity as
much as for performance.

Another concern is that whatever form you might use to display anonymous
types might clash with future C# syntax. So maybe "Anon{short, uint}" would
be safer (and, perhaps, clearer) than my original proposal.

Best regards
Matt

**Comment by stakx** [comment]
Thanks for the detailed reply!

> I can see two major uses of the library. One is source code generation [...]. The other is diagnostics [...].

I have mostly diagnostics in mind. (For source code generation, one is probably far better off using Roslyn.) So I'd say what you're calling "best effort" should indeed be the default behavior.

> source code generation, and for this purpose it should generate only valid C# (or Visual Basic), or throw an exception

I'd feel uncomfortable with exceptions being thrown. I'd really like these methods to be non-throwing.

Some alternatives:

1. Convert `AppendFormattedName` and `GetFormattedName` to the `Try` pattern so it can return `false` in the case of non-success. However, this would make them much more impractical, e.g. you could no longer chain the former with other `StringBuilder.Append...` methods.

2. Have both `Try...` and non-`Try...` variants. The problem here is that due to how the pattern usually works, the non-`Try...` variants would be "strict" and the `Try...` ones would be either strict or non-strict (depending on the options specified). So the "best effort" variants would end up being the impractical methods (see 1 above). Since the library is meant mostly for diagnostics, this seems like the wrong approach.

3. Add a new method that checks whether a type's name is expressible in the targeted language. If someone needs "strict mode", they could just validate a type's name using that method.

I clearly tend towards 3 but I feel that having a "strict mode" isn't a huge priority, and possibly even outside the intended scope of this library.

> In best-efforts mode, I don't particularly care if there is ambiguity as to the exact identity of the type in edge cases [...]. As for anonymous types, although including field names would help disambiguate, it would not identify the type [...]

I think your argument against including property names are sound, I agree with you that they don't need to be included.

> Another concern is that whatever form you might use to display anonymous types might clash with future C# syntax.

Hmm. Good point. I'm not sure what's the right approach here, but TBH I'm not overly concerned with this right now. I'd rather not transform anonymous types' names, or risk running into this problem later, than inventing some syntax like `Anon { ... }` that doesn't actually exist in C#.

**Comment by stakx** [comment]
All things considered, I really like your original suggestion:

> I wonder if the library could return something prettier, e.g. "{string, int}"?

**Comment by pmg23** [comment]
"Best efforts" is the important use case for me too; you can always add "strict mode" later as an option (along with Try variants) if required. I think it should be enough for now to document that, in the default mode, the behaviour is best-efforts and non-throwing. (I wasn't sure as you mentioned in #4 that you might throw for some inputs.)

**Comment by stakx** [comment]
@pmg23 -

> I think it should be enough for now to document that, in the default mode, the behaviour is best-efforts and non-throwing.

Good idea. Right now the readme only documents what the additional options do, but not what the default option does (generally, it results in the most compact representation). I'll try to also add a statement about the library's supposed nonthrowyness.

> non-throwing. (I wasn't sure as you mentioned in #4 that you might throw for some inputs.)

That's understandable. Speaking of #4, I wrote that issue at an early stage, right now I'm not even sure whether having VB.NET formatting support would even be desirable, given that C#'s status as the canonical .NET language / lingua franca perhaps it's not needed for diagnostic purposes.

**Comment by stakx** [comment]
@pmg23 - sorry to bother again, but it just occurred to me to check how IntelliSense displays these kinds of types:

![anonymous-type-syntax](https://user-images.githubusercontent.com/104481/40831318-fb5ce22e-6588-11e8-9514-77cf385330c8.png)

Or, in the case of nested anonymous types:

![nested-anonymous-type-syntax](https://user-images.githubusercontent.com/104481/40831659-e08f52e6-6589-11e8-9b17-e1812a2cc2f9.png)

(The `'a`, `'b` stuff would probably not be applicable here.)

Any thoughts on this? I know that `new { <per-property-list-of-type-and-name> }` directly goes against several points I've already made above... but then IntelliSense is kind of "official". Do you think it should be our guide here?

**Comment by pmg23** [comment]
I think `"{string Name, int Age, {string Color}}"` is fine, if that is what you mean?

Alternatively `"new {string Name, int Age, new {string Color}}"` is also OK, although it will look funny when you nest it, e.g. type of `new[] {new {Name = "foo"}}` will be `"new {string Name}[]"`.

I suggest not to compromise on functionality (or add API complexity) for the sake of performance. You could still get good amortised performance by simply caching all results (using a `ConcurrentDictionary<(Type, TypeNameFormatOptions), string>` say) - or let the caller do this. If you did cache internally this would also obviate the need for a separate `AppendFormattedName` method.

**Comment by stakx** [comment]
> You could still get good amortised performance by simply caching all results [...] or let the caller do this.

Since the library as a whole hasn't been optimized yet, adding internal caching is probably premature. So to start off with, let's do this as an uncached opt-out feature. (Anonymous types are typically fairly rare, anyways.)
